[default]
max_input_length = 120
epochs = 10
batch_size = 10
number_trails = 20

[path]
data_files = "datasets/downloads"
dataset = "datasets/dataset.csv"

[path.plot]
dataset_length_dist = "outputs/plots/len_dist.png"

[tunning]
batch_size = [8, 16]
learning_rate = [5e-7, 1e-5]
number_trails = 32
epochs = 50

[tuned]
batch_size = 8
learning_rate = 1.6644170133107985e-6
epochs = 50